
$word = New-Object -ComObject Word.Application
$word.Visible = $false
$doc = $word.Documents.Add()
$sel = $doc.ActiveWindow.Selection

$doc.PageSetup.TopMargin    = 72
$doc.PageSetup.BottomMargin = 72
$doc.PageSetup.LeftMargin   = 85
$doc.PageSetup.RightMargin  = 85

function H1($t) {
    $s = $doc.ActiveWindow.Selection
    $s.Style = $doc.Styles.Item("Heading 1")
    $s.TypeText($t)
    $s.TypeParagraph()
}
function H2($t) {
    $s = $doc.ActiveWindow.Selection
    $s.Style = $doc.Styles.Item("Heading 2")
    $s.TypeText($t)
    $s.TypeParagraph()
}
function H3($t) {
    $s = $doc.ActiveWindow.Selection
    $s.Style = $doc.Styles.Item("Heading 3")
    $s.TypeText($t)
    $s.TypeParagraph()
}
function P($t) {
    $s = $doc.ActiveWindow.Selection
    $s.Style = $doc.Styles.Item("Normal")
    $s.TypeText($t)
    $s.TypeParagraph()
}
function PB($label, $t) {
    $s = $doc.ActiveWindow.Selection
    $s.Style = $doc.Styles.Item("Normal")
    $s.Font.Bold = $true
    $s.TypeText($label)
    $s.Font.Bold = $false
    $s.TypeText($t)
    $s.TypeParagraph()
}

# ─── Title ───────────────────────────────────────────────────────────────────
$s = $doc.ActiveWindow.Selection
$s.Style = $doc.Styles.Item("Title")
$s.TypeText("Technical Documentation")
$s.TypeParagraph()
$s.Style = $doc.Styles.Item("Subtitle")
$s.TypeText("Project: LuyMoney - Flutter Application")
$s.TypeParagraph()
$s.TypeParagraph()

# ─── 1. Introduction ─────────────────────────────────────────────────────────
H1 "1. Introduction (សេចក្តីផ្តើម)"
P "Project LuyMoney គឺជា Mobile Application សម្រាប់ Android, iOS, និង Web ដែលបង្កើតដោយ Flutter Framework។ Application ផ្តល់ Financial Education Content (Videos, Articles), Chat Support, Subscription Management, Admin Panel, Multi-language (EN/KH/ZH), Multi-theme (Black/White/Blue)។ Backend ប្រើ Firebase (Auth, Firestore, Storage, Messaging, Analytics, Crashlytics, App Check)។ State Management ប្រើ GetX Pattern (MVC)។"

# ─── 2. Architecture ─────────────────────────────────────────────────────────
H1 "2. Architecture Overview"
P "Project ប្រើ Clean Architecture + GetX MVC:"
P "   Presentation Layer  : Views (UI Screens) + Controllers (Business Logic)"
P "   Domain Layer        : Repository Interfaces (Abstract Classes)"
P "   Data Layer          : Models (Data Structures) + Providers (Implementations)"
P "   Services Layer      : Global Services (Auth, Storage, Notification, Analytics)"
P "   Shared Layer        : Constants, Themes, Translations, Widgets, Utils"

# ─── 3. Root Files ────────────────────────────────────────────────────────────
H1 "3. Root Files (lib/)"

H2 "main.dart"
PB "តួនាទី: "     "Entry Point ចម្បងរបស់ Application"
PB "គោលបំណង: "   "Initialize Services ទាំងអស់ ហើយ Launch App"
PB "ដំណើការ: "    "1) Firebase.initializeApp()  2) FirebaseAppCheck.activate()  3) GetStorage.init()  4) Hive.initFlutter()  5) Timezone init  6) Screen orientation  7) ThemeController + LanguageController  8) runApp()  9) StorageService + AuthService + NotificationService (background)"
PB "Function: "   "main() async, class LuyMoneyApp extends StatelessWidget"
PB "Dependencies: " "firebase_core, firebase_app_check, get, get_storage, hive_flutter, timezone"

H2 "app_config.dart"
PB "តួនាទី: "     "App Configuration Constants"
PB "គោលបំណង: "   "Central config file ជាទីកន្លែងតែមួយ ដែលរក្សា URL, App Name, Version"
PB "ដំណើការ: "    "Static class ដែល expose constants: appName, appVersion, telegramSupportUrl, privacyPolicyUrl, termsOfServiceUrl, faqUrl"
PB "សម្រាប់ធ្វើអ្វី: " "បើចង់ផ្លាស់ URL ឬ App Name - Edit File នេះតែមួយ"

H2 "firebase_options.dart"
PB "តួនាទី: "     "Firebase Configuration (Auto-generated by FlutterFire CLI)"
PB "គោលបំណង: "   "ផ្ទុក API Keys, App IDs, Project IDs សម្រាប់ Platform នីមួយៗ"
PB "ដំណើការ: "    "DefaultFirebaseOptions.currentPlatform return FirebaseOptions ត្រឹមត្រូវតាម Platform (Android/iOS/Web/Windows)"
PB "សម្រាប់ធ្វើអ្វី: " "Firebase.initializeApp(options:) ប្រើ File នេះ - Do NOT edit manually"

# ─── 4. Routes ───────────────────────────────────────────────────────────────
H1 "4. Routes (lib/app/routes/)"
P "Folder នេះគ្រប់គ្រង Navigation ទាំងអស់ក្នុង App"

H2 "app_routes.dart"
PB "តួនាទី: "     "Route Constants Definition"
PB "គោលបំណង: "   "Define Route Names ជា String Constants ដើម្បី Avoid typos"
PB "ដំណើការ: "    "Class Routes ជាមួយ static const strings: SPLASH, LOGIN, REGISTER, HOME, ADMIN, SUBSCRIPTION, PAYMENT, VIDEOS, ARTICLES, SUPPORT, SETTINGS, PROFILE..."
PB "សម្រាប់ធ្វើអ្វី: " "ប្រើ Routes.HOME ជំនួស '/home' ដើម្បីការពារ typo"

H2 "app_pages.dart"
PB "តួនាទី: "     "Route-to-Widget Mapping"
PB "គោលបំណង: "   "Map Routes Names ទៅ Widget Views + Bindings + Middlewares"
PB "ដំណើការ: "    "Class AppPages ដែលមាន INITIAL = Routes.SPLASH និង List<GetPage> routes. GetX ប្រើ routes list នេះ Navigate រួមជាមួយ Middleware"
PB "សម្រាប់ធ្វើអ្វី: " "Register route ថ្មី → Add GetPage() ត្រង់នេះ"

H2 "middlewares/auth_middleware.dart"
PB "តួនាទី: "     "Authentication Route Guard"
PB "គោលបំណង: "   "ការពារ Routes ដែលត្រូវការ Login"
PB "ដំណើការ: "    "extends GetMiddleware → override redirect() → check authService.isLoggedIn → if false redirect to LOGIN"
PB "ប្រើលើ Routes: " "HOME, SUBSCRIPTION, PAYMENT, VIDEOS, ARTICLES, SUPPORT, SETTINGS, PROFILE, ADMIN"

H2 "middlewares/subscription_middleware.dart"
PB "តួនាទី: "     "Subscription Route Guard"
PB "គោលបំណង: "   "ការពារ Premium Content Routes"
PB "ដំណើការ: "    "Check hasActiveSubscription → if false redirect to SUBSCRIPTION"
PB "ប្រើលើ Routes: " "VIDEOS, ARTICLES, VIDEO_DETAIL, ARTICLE_DETAIL"

H2 "middlewares/admin_middleware.dart"
PB "តួនាទី: "     "Admin Route Guard"
PB "គោលបំណង: "   "ការពារ Admin Routes ពី User ធម្មតា"
PB "ដំណើការ: "    "Check authService.isAdmin → if false redirect to HOME"
PB "ប្រើលើ Routes: " "ADMIN, ADMIN_USERS, ADMIN_CONTENT, ADMIN_ANALYTICS, ADMIN_NOTIFICATIONS"

# ─── 5. Services ─────────────────────────────────────────────────────────────
H1 "5. Services (lib/app/services/)"
P "Services ជា Global GetxService ដែល Register ក្នុង main() ហើយ Available ពេញ App"

H2 "auth_service.dart"
PB "តួនាទី: "     "Firebase Authentication Service"
PB "គោលបំណង: "   "គ្រប់គ្រង User Authentication State ទូទៅ"
PB "ដំណើការ: "    "Listen to Firebase authStateChanges() → load UserModel from Firestore → expose isLoggedIn, isAdmin, hasActiveSubscription, currentUser, firebaseUser"
PB "Methods: "    "signInWithEmail(), registerWithEmail(), sendPasswordResetEmail(), signOut(), updateUserProfile(), deleteUserData(), refreshUser()"
PB "Observables: " "Rx<UserModel?> currentUser"
PB "សម្រាប់ធ្វើអ្វី: " "ប្រើ Get.find<AuthService>() ពីទីណាក៏បាន ដើម្បីដឹង User Info"

H2 "notification_service.dart"
PB "តួនាទី: "     "Push Notification Service"
PB "គោលបំណង: "   "គ្រប់គ្រង Local Notifications + Firebase Cloud Messaging (FCM)"
PB "ដំណើការ: "    "1) Init flutter_local_notifications  2) Create Android Notification Channel  3) Request FCM Permission  4) Listen to onMessage → show local notification  5) Handle background messages"
PB "Methods: "    "scheduleExpiryReminders(), cancelAllReminders(), getFCMToken(), _showLocalNotification()"
PB "សម្រាប់ធ្វើអ្វី: " "Send Subscription Expiry Reminders (7 days, 1 day, expiry day)"

H2 "storage_service.dart"
PB "តួនាទី: "     "Local Storage Service Wrapper"
PB "គោលបំណង: "   "Wrap GetStorage ដើម្បី Typed access ជា Central point"
PB "ដំណើការ: "    "Delegate read/write/remove/erase ទៅ GetStorage + helper keys (themeKey, langKey, bookmarkedVideosKey...)"
PB "Methods: "    "toggleVideoBookmark(), toggleArticleBookmark(), isVideoBookmarked(), isArticleBookmarked()"
PB "Keys: "       "theme, lang, remember_email, biometric_enabled, notif_subscription, notif_content, notif_promo, bookmarked_videos, bookmarked_articles"

H2 "analytics_service.dart"
PB "តួនាទី: "     "Firebase Analytics Service"
PB "គោលបំណង: "   "Track User Events (screen views, subscriptions, content views)"
PB "ដំណើការ: "    "Wrap FirebaseAnalytics → logEvent() for custom events"
PB "សម្រាប់ធ្វើអ្វី: " "Monitor User behavior ក្នុង Firebase Analytics Dashboard"

# ─── 6. Data Models ──────────────────────────────────────────────────────────
H1 "6. Data Models (lib/app/data/models/)"
P "Models ជា Data Structures ដែល Map ជាមួយ Firestore Documents"

H2 "user_model.dart"
PB "តួនាទី: "     "User Data Model"
PB "Fields: "     "id, name, email, phone, avatarUrl, role (user/admin), subscription, createdAt, biometricEnabled"
PB "Methods: "    "fromFirestore(), toFirestore(), toMap(), copyWith()"
PB "Computed: "   "isAdmin (role == admin), hasActiveSubscription"
PB "Firestore: "  "Collection: users / Document: {uid}"

H2 "content_model.dart"
PB "តួនាទី: "     "Video and Article Data Models"
PB "VideoModel Fields: " "id, title, description, videoUrl, thumbnailUrl, category, isPremium, viewCount, durationMinutes, publishedAt"
PB "ArticleModel Fields: " "id, title, content, coverImageUrl, category, isPremium, viewCount, readTimeMinutes, publishedAt"
PB "Methods: "    "fromFirestore(), toMap()"
PB "Firestore: "  "Collections: videos, articles"

H2 "subscription_model.dart"
PB "តួនាទី: "     "Subscription Data Model"
PB "Fields: "     "id, userId, planId, startDate, expiryDate, isActive, paymentMethod, transactionId, createdAt"
PB "Computed: "   "isExpired (DateTime.now().isAfter(expiryDate)), daysRemaining"
PB "Firestore: "  "Collection: subscriptions"

H2 "chat_model.dart"
PB "តួនាទី: "     "Chat Message Data Model"
PB "Fields: "     "id, senderId, message, timestamp, type (text/image), imageUrl, isFromAdmin"
PB "Enum: "       "MessageType { text, image }"
PB "Firestore: "  "Collection: chats/{userId}/messages"

# ─── 7. Domain / Repositories ─────────────────────────────────────────────────
H1 "7. Domain Layer (lib/app/domain/repositories/)"
P "Repository Interfaces (Abstract Classes) - Domain Layer"

H2 "auth_repository.dart"
PB "តួនាទី: "     "Abstract Interface for Authentication"
PB "Methods: "    "signIn(), register(), signOut(), resetPassword(), getCurrentUser()"
PB "គោលបំណង: "   "Define contract ដែល Implementation ត្រូវ follow"

H2 "content_repository.dart"
PB "តួនាទី: "     "Abstract Interface for Content"
PB "Methods: "    "getVideos(), getArticles(), getVideoById(), getArticleById()"

H2 "subscription_repository.dart"
PB "តួនាទី: "     "Abstract Interface for Subscription"
PB "Methods: "    "getCurrentSubscription(), subscribe(), cancelSubscription()"

# ─── 8. Data Providers ────────────────────────────────────────────────────────
H1 "8. Data Providers (lib/app/data/providers/)"

H2 "auth_repository_impl.dart"
PB "តួនាទី: "     "Firebase Auth Repository Implementation"
PB "គោលបំណង: "   "Implement auth_repository.dart interface ដោយប្រើ Firebase Auth + Firestore"

H2 "content_repository_impl.dart"
PB "តួនាទី: "     "Firestore Content Repository Implementation"
PB "គោលបំណង: "   "Fetch Videos + Articles ពី Firestore collections"

# ─── 9. Modules ──────────────────────────────────────────────────────────────
H1 "9. Modules (lib/app/modules/)"
P "Modules = Feature-based Organization. Module នីមួយៗមាន bindings/, controllers/, views/"

H2 "9.1 Auth Module (modules/auth/)"

H3 "auth_binding.dart"
PB "តួនាទី: "     "GetX Dependency Injection for Auth"
PB "ដំណើការ: "    "Get.lazyPut<AuthController>(() => AuthController(), fenix: true)"
PB "fenix: true: " "Recreate Controller ថ្មី ប្រសិនបើ Disposed (ការពារ TextController disposed error)"

H3 "auth_controller.dart"
PB "តួនាទី: "     "Authentication Business Logic Controller"
PB "Form Fields: " "emailController, passwordController, confirmPasswordController, nameController, phoneController"
PB "States: "      "isLoading, isPasswordVisible, rememberMe, otpSent"
PB "Methods: "     "login() - signin + navigate Admin or Home, register() - create account + navigate Subscription, sendPasswordReset(), authenticateWithBiometric(), validateEmail/Password/Name/ConfirmPassword()"
PB "Navigation: "  "After login: check isAdmin → ADMIN or HOME. After register → SUBSCRIPTION"

H3 "splash_view.dart"
PB "តួនាទី: "     "Splash Screen (Loading Screen)"
PB "ដំណើការ: "    "1) Fade + Scale Animation (1.5s)  2) After 2.5s → check isAdmin → ADMIN, hasSubscription → HOME, else → SUBSCRIPTION, not logged in → LOGIN"
PB "Animation: "   "FadeTransition (0.3→1) + ScaleTransition (0.8→1.0) using elasticOut curve"

H3 "login_view.dart"
PB "តួនាទី: "     "Login Screen UI"
PB "UI Elements: " "Logo, Email Field, Password Field, Remember Me, Forgot Password Link, Login Button (GoldButton), Register Link"
PB "Validation: "  "Email format + Password min 8 chars"

H3 "register_view.dart"
PB "តួនាទី: "     "Registration Screen UI"
PB "UI Elements: " "Full Name, Email, Phone Number, Password, Confirm Password Fields + Register Button"

H3 "forgot_password_view.dart"
PB "តួនាទី: "     "Password Reset Screen UI"
PB "ដំណើការ: "    "Enter email → Firebase sendPasswordResetEmail() → Show success state"

H2 "9.2 Home Module (modules/home/)"

H3 "home_binding.dart"
PB "តួនាទី: "     "Dependency Injection for Home"
PB "ដំណើការ: "    "lazyPut HomeController + ContentController"

H3 "home_controller.dart"
PB "តួនាទី: "     "Home Screen Business Logic"
PB "Methods: "    "Navigate to Videos, Articles, Support, Settings, Subscription"
PB "States: "     "Observe AuthService.currentUser for personalized greeting"

H3 "home_view.dart"
PB "តួនាទី: "     "Home Screen UI - Main Dashboard"
PB "UI Sections: " "1) Welcome + Username  2) Subscription Status Banner  3) Stats (Videos, Articles, Topics)  4) Latest Videos (horizontal scroll)  5) Latest Articles (list)"
PB "Responsive: "  "Video list height = screenWidth * 0.55"

H2 "9.3 Content Module (modules/content/)"

H3 "content_controller.dart"
PB "តួនាទី: "     "Content (Videos/Articles) Business Logic"
PB "Methods: "    "fetchVideos(), fetchArticles(), filterByCategory(), searchContent(), toggleBookmark()"
PB "States: "     "videos, articles, isLoading, selectedCategory, searchQuery"

H3 "videos_view.dart"
PB "តួនាទី: "     "Videos List Screen"
PB "UI: "         "Search bar, Category Chips filter, Videos ListView, Empty state"

H3 "articles_view.dart"
PB "តួនាទី: "     "Articles List Screen"
PB "UI: "         "Search bar, Category Chips filter, Articles ListView, Empty state"

H3 "video_detail_view.dart"
PB "តួនាទី: "     "Video Player Detail Screen"
PB "UI: "         "YouTube/Video Player, Title, Description, Category Badge, View count, Duration"

H3 "article_detail_view.dart"
PB "តួនាទី: "     "Article Reading Screen"
PB "UI: "         "SliverAppBar with Cover Image (screenHeight*0.3), Author info, HTML Content rendered"

H2 "9.4 Settings Module (modules/settings/)"

H3 "settings_controller.dart"
PB "តួនាទី: "     "Settings Business Logic"
PB "Methods: "    "updateProfile(), uploadAvatar(), changePassword(), deleteAccount(), toggleNotifications, rateApp(), openUrl(), signOut()"
PB "Features: "   "Profile update → Firestore, Avatar upload → Firebase Storage, Change Password → Firebase reauthenticate + updatePassword, Delete Account → Delete Firestore doc + Firebase Auth delete"

H3 "language_controller.dart"
PB "តួនាទី: "     "Multi-language Controller"
PB "Supported: "  "English (en_US), Khmer (km_KH), Chinese (zh_CN)"
PB "ដំណើការ: "    "changeLanguage() → update currentLocale observable + Get.updateLocale() + persist to GetStorage"

H3 "settings_view.dart"
PB "តួនាទី: "     "Settings Main Screen"
PB "Sections: "   "ACCOUNT (Profile, Change Password, Delete Account), ADMIN PANEL (admin only), APPEARANCE (Theme selector, Language), NOTIFICATIONS (toggles), SUBSCRIPTION, SUPPORT, LEGAL, Version, Logout"

H3 "profile_view.dart"
PB "តួនាទី: "     "User Profile Edit Screen"
PB "UI: "         "Avatar (tap to change), Name field, Email (readonly), Phone field, Save button, Change Password dialog, Delete Account"
PB "Fallback: "   "ប្រើ Firebase Auth data ប្រសិនបើ Firestore មិនទាន់ Load"

H2 "9.5 Support Module (modules/support/)"

H3 "support_controller.dart"
PB "តួនាទី: "     "Chat Support Business Logic"
PB "ដំណើការ: "    "1) Listen to Firestore chats/{uid}/messages in realtime  2) sendMessage() → add to Firestore  3) sendImage() → upload to Storage → add message"
PB "Note: "       "ប្រើ firebaseUser?.uid (not currentUser.value?.id) ដើម្បីការពារ null UID error"

H3 "support_view.dart"
PB "តួនាទី: "     "Chat Support Screen UI"
PB "Tabs: "       "1) In-App Chat (realtime Firestore messages, image send)  2) Telegram (link to Telegram community)"
PB "UI: "         "Message bubbles (User=gold, Admin=surface), Image messages, Send button with loading"

H2 "9.6 Subscription Module (modules/subscription/)"

H3 "subscription_controller.dart"
PB "តួនាទី: "     "Subscription Purchase Business Logic"
PB "Plans: "      "Monthly, Quarterly, Biannual, Annual"
PB "Payment: "    "ABA Pay, Wing Money, Credit Card, PayPal (UI mockup)"

H3 "promo_code_controller.dart"
PB "តួនាទី: "     "Promo Code Validation"
PB "ដំណើការ: "    "Check promo code against Firestore → apply discount"

H3 "referral_controller.dart"
PB "តួនាទី: "     "Referral System"
PB "ដំណើការ: "    "Generate/share referral link using share_plus"

H3 "subscription_view.dart"
PB "តួនាទី: "     "Subscription Plans Screen"
PB "UI: "         "Plan Cards (Monthly/Quarterly/Biannual/Annual), Price comparison, Subscribe button, Promo code input"

H3 "payment_view.dart"
PB "តួនាទី: "     "Payment Screen"
PB "UI: "         "Order summary, Payment method selection, Pay button"

H2 "9.7 Admin Module (modules/admin/)"

H3 "admin_binding.dart"
PB "តួនាទី: "     "Dependency Injection for Admin"
PB "ដំណើការ: "    "lazyPut AdminController"

H3 "admin_controller.dart"
PB "តួនាទី: "     "Admin Panel Business Logic (Central)"
PB "Features: "   "Users Management, Content Management, Analytics, Notifications"
PB "User Methods: "    "fetchUsers(), extendUserSubscription(), deactivateUser(), deleteUser()"
PB "Content Methods: " "fetchContent(), addVideo(), addArticle(), deleteVideo(), deleteArticle()"
PB "Analytics: "       "fetchAnalytics() - totalUsers, activeUsers, expiredUsers, monthlyRevenue, totalRevenue, revenueChartData"
PB "Notifications: "   "sendPushNotification() → save to admin_notifications collection → Cloud Function picks up"

H3 "admin_view.dart"
PB "តួនាទី: "     "Admin Panel Main Layout"
PB "Layout: "     "Wide Screen → Side Navigation (200px) + Content Area. Mobile → Bottom Navigation + Content Area"
PB "Tabs: "       "Users, Content, Analytics, Notify"
PB "Navigation: " "Home button → Get.offAllNamed('/home')"

H3 "admin_users_view.dart"
PB "តួនាទី: "     "Admin Users Management Screen"
PB "Features: "   "Search users, Filter (All/Active/Expired/Free), View user details, Extend subscription, Deactivate/Delete user"

H3 "admin_content_view.dart"
PB "តួនាទី: "     "Admin Content Management Screen"
PB "Features: "   "Tab Videos/Articles, Add/Edit/Delete Video, Add/Delete Article"
PB "Add Video Fields: " "Title, YouTube URL, Category, Description"
PB "Add Article Fields: " "Title, Cover Image URL, Category, Description"

H3 "admin_analytics_view.dart"
PB "តួនាទី: "     "Admin Analytics Dashboard"
PB "Charts: "     "Revenue Line Chart (6 months), User Distribution Pie Chart, Stats Cards (Total/Active/Expired/Free users, Revenue)"

H3 "admin_notifications_view.dart"
PB "តួនាទី: "     "Admin Push Notification Sender"
PB "Features: "   "Title, Message, Target (All/Active/Expiring), Send → save to Firestore admin_notifications"

# ─── 10. Shared Layer ─────────────────────────────────────────────────────────
H1 "10. Shared Layer (lib/app/shared/)"

H2 "10.1 Constants"

H3 "constants/app_colors.dart"
PB "តួនាទី: "     "Global Color Constants"
PB "Themes: "     "Black Theme (blackBackground #0A0A0A, blackSurface #1A1A1A...), White Theme, Blue Theme"
PB "Brand: "      "gold #D4AF37, goldDark, goldLight, goldAccent"
PB "Status: "     "success, warning, error, info (with light variants)"
PB "Gradient: "   "goldGradient (D4AF37 → F0C832 → B8960C), darkGradient"

H3 "constants/app_dimensions.dart"
PB "តួនាទី: "     "Global Spacing/Size Constants"
PB "ដំណើការ: "    "Static constants for padding, margins, border radius, icon sizes"

H2 "10.2 Themes"

H3 "themes/app_themes.dart"
PB "តួនាទី: "     "Theme Configuration + Theme Controller"
PB "AppTheme enum: " "white, black, oldBlue"
PB "ThemeController: " "GetxController - switchTheme(), persist to GetStorage, update System UI overlay"
PB "AppThemes.getTheme(): " "Return ThemeData for each AppTheme"
PB "AppColorExtension: " "ThemeExtension for easy color access via context.appColors"

H2 "10.3 Translations"

H3 "translations/app_translations.dart"
PB "តួនាទី: "     "Multi-language Translation Configuration"
PB "ដំណើការ: "    "extends Translations → Map<String, Map<String, String>> keys { 'en_US': enUS, 'km_KH': kmKH, 'zh_CN': zhCN }"

H3 "translations/locales/en_us.dart"
PB "តួនាទី: "     "English (US) Translation Strings"
PB "Keys: "       "Auth, Home, Content, Support, Settings, Errors, Notifications, Payment, General keys"

H3 "translations/locales/km_kh.dart"
PB "តួនាទី: "     "Khmer (Cambodia) Translation Strings"
PB "Keys: "       "Same keys as en_us.dart but in Khmer language"

H3 "translations/locales/zh_cn.dart"
PB "តួនាទី: "     "Chinese (Simplified) Translation Strings"
PB "Keys: "       "Same keys in Chinese"

H2 "10.4 Utils"

H3 "utils/responsive_layout.dart"
PB "តួនាទី: "     "Responsive Layout Utilities"
PB "ResponsiveLayout Widget: " "Switch Mobile/Tablet/Desktop layout based on screen width (600/1024 breakpoints)"
PB "AdaptiveGrid Widget: " "Auto 1/2/3 column grid"
PB "ResponsiveContext Extension: " "context.rSize(x) - scale by screen width, context.rFont(x) - responsive font, context.screenWidth/Height, context.isMobile/isTablet/isDesktop"

H3 "utils/app_utils.dart"
PB "តួនាទី: "     "Global Utility Functions"
PB "AppSnackbar: " "success(), error(), warning() - Show GetX snackbars with consistent styling"

H2 "10.5 Widgets"

H3 "widgets/gold_button.dart"
PB "តួនាទី: "     "Custom Primary Button Widget (Gold Gradient)"
PB "Props: "      "label, onPressed, isLoading, isOutlined"
PB "ដំណើការ: "    "isLoading → show CircularProgressIndicator, isOutlined → border only, normal → gold gradient fill"

H3 "widgets/custom_text_field.dart"
PB "តួនាទី: "     "Custom Styled Input Field"
PB "Props: "      "controller, label, hint, validator, isPassword, readOnly, prefixIcon, keyboardType"
PB "Features: "   "Password toggle visibility, consistent styling across themes"

H3 "widgets/subscription_banner.dart"
PB "តួនាទី: "     "Subscription Status Banner Widget"
PB "ដំណើការ: "    "Show status based on subscription: Active (green), Expiring (yellow warning), Expired/None (gold - tap to subscribe)"

H3 "widgets/category_chips.dart"
PB "តួនាទី: "     "Category Filter Chips Widget"
PB "ដំណើការ: "    "Horizontal scrollable chips for filtering content by category (Finance, Investment, Trading...)"

H3 "widgets/lock_overlay.dart"
PB "តួនាទី: "     "Premium Content Lock Overlay"
PB "ដំណើការ: "    "Show lock icon + 'Subscribe to unlock' over premium content ប្រសិនបើ user គ្មាន subscription"

H3 "widgets/shimmer_card.dart"
PB "តួនាទី: "     "Loading Skeleton Shimmer Widget"
PB "ដំណើការ: "    "Show animated shimmer placeholder ខណៈ content loading"

H3 "widgets/video_card.dart"
PB "តួនាទី: "     "Video Item Card Widget"
PB "UI: "         "Thumbnail, Title, Category, Duration, View count, Premium lock (if applicable), Bookmark button"

H3 "widgets/article_card.dart"
PB "តួនាទី: "     "Article Item Card Widget"
PB "UI: "         "Cover image, Title, Category, Read time, View count, Premium lock, Bookmark button"

H3 "widgets/widgets.dart"
PB "តួនាទី: "     "Barrel Export File"
PB "ដំណើការ: "    "Re-export all widgets ដើម្បី import file តែមួយ"

# ─── 11. Firebase Structure ────────────────────────────────────────────────────
H1 "11. Firebase / Firestore Database Structure"

H2 "Collections Overview"
P "users/{uid}                     - User profiles + role"
P "chats/{uid}/messages/{msgId}    - Chat messages per user"
P "videos/{videoId}                - Video content"
P "articles/{articleId}            - Article content"
P "subscriptions/{subId}           - User subscriptions"
P "admin_notifications/{notifId}   - Queued push notifications"

H2 "users Collection"
P "Fields: id, name, email, phone, avatarUrl, role (user/admin), biometricEnabled, createdAt"

H2 "videos Collection"
P "Fields: title, description, videoUrl, thumbnailUrl, category, isPremium, viewCount, durationMinutes, publishedAt, createdAt"

H2 "articles Collection"
P "Fields: title, content, coverImageUrl, category, isPremium, viewCount, readTimeMinutes, publishedAt, createdAt"

H2 "subscriptions Collection"
P "Fields: userId, planId, startDate, expiryDate, isActive, paymentMethod, transactionId, createdAt"

# ─── 12. Android Configuration ─────────────────────────────────────────────────
H1 "12. Android Configuration"

H2 "android/app/build.gradle.kts"
PB "Package: "    "com.luymoney.app"
PB "minSdk: "     "flutter.minSdkVersion (21+)"
PB "Plugins: "    "com.android.application, kotlin-android, com.google.gms.google-services, com.google.firebase.crashlytics, dev.flutter.flutter-gradle-plugin"
PB "Features: "   "isCoreLibraryDesugaringEnabled = true (required for flutter_local_notifications)"
PB "Dependencies: " "coreLibraryDesugaring desugar_jdk_libs:2.1.4"

H2 "android/app/src/main/kotlin/com/luymoney/app/MainActivity.kt"
PB "Package: "    "com.luymoney.app"
PB "Class: "      "MainActivity extends FlutterActivity"

H2 "android/app/google-services.json"
PB "តួនាទី: "     "Firebase Android Configuration"
PB "Content: "    "project_id, storage_bucket, mobilesdk_app_id, package_name, api_key"

# ─── 13. Key Dependencies ─────────────────────────────────────────────────────
H1 "13. Key Dependencies (pubspec.yaml)"
P "State Management  : get ^4.x (GetX - Controller, Routing, State)"
P "Local Storage     : get_storage ^2.x (Key-Value Storage), hive_flutter ^1.x (Box Storage)"
P "Firebase Core     : firebase_core, firebase_auth, cloud_firestore, firebase_storage"
P "Firebase Extra    : firebase_analytics, firebase_crashlytics, firebase_messaging, firebase_app_check"
P "UI                : cached_network_image, shimmer, fl_chart (charts)"
P "Media             : image_picker, video_player, youtube_player_flutter"
P "Auth              : local_auth (biometric)"
P "Payment           : flutter_stripe, in_app_purchase"
P "Utils             : url_launcher, share_plus, intl (date format), package_info_plus"
P "Notifications     : flutter_local_notifications, timezone"

# ─── Save ─────────────────────────────────────────────────────────────────────
$savePath = "D:\Data\Lesson\Flutter\Project Phana\luy_money\LuyMoney_Technical_Documentation.docx"
$doc.SaveAs([ref]$savePath, 16)  # 16 = wdFormatDocumentDefault (.docx)
$doc.Close()
$word.Quit()

Write-Output "Document saved to: $savePath"
