// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSOcrcTNQcvBqPFB9mfmPphQ3AlyKJu-8',
    appId: '1:496853827418:web:e713dfb48f61dec8cc3d63',
    messagingSenderId: '496853827418',
    projectId: 'luymoney-8783a',
    authDomain: 'luymoney-8783a.firebaseapp.com',
    storageBucket: 'luymoney-8783a.firebasestorage.app',
    measurementId: 'G-EYP1V1YTJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1SSsPAo8qAh_NpILtvs86Mm7q9vLV-a8',
    appId: '1:496853827418:android:1a291f51ce67fd5ecc3d63',
    messagingSenderId: '496853827418',
    projectId: 'luymoney-8783a',
    storageBucket: 'luymoney-8783a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1HCuBR77ClSpIsNObExETq7KJ0uNGIk4',
    appId: '1:496853827418:ios:7fb7134c8ea476a6cc3d63',
    messagingSenderId: '496853827418',
    projectId: 'luymoney-8783a',
    storageBucket: 'luymoney-8783a.firebasestorage.app',
    iosBundleId: 'com.example.luyMoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1HCuBR77ClSpIsNObExETq7KJ0uNGIk4',
    appId: '1:496853827418:ios:7fb7134c8ea476a6cc3d63',
    messagingSenderId: '496853827418',
    projectId: 'luymoney-8783a',
    storageBucket: 'luymoney-8783a.firebasestorage.app',
    iosBundleId: 'com.example.luyMoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSOcrcTNQcvBqPFB9mfmPphQ3AlyKJu-8',
    appId: '1:496853827418:web:77e70c949808399ccc3d63',
    messagingSenderId: '496853827418',
    projectId: 'luymoney-8783a',
    authDomain: 'luymoney-8783a.firebaseapp.com',
    storageBucket: 'luymoney-8783a.firebasestorage.app',
    measurementId: 'G-PD1841LMKZ',
  );
}
